(function(q,h,g){function d(a,b){return this instanceof d?this.init(a,b):new d(a,b)}function l(a,b){return a.changedTouches?a.changedTouches[0][b]:a[b]}function r(a){return m(a,function(a){return s.style[a]!==g})}function v(a,b,c){var e=n[b];e?a[e]=c:a[b]!==g?(n[b]=b,a[b]=c):m(u,function(e){e=o(e)+o(b);if(a[e]!==g)return n[b]=e,a[e]=c,!0})}function w(a){if(s.style[a]!==g)return a;var b;m(u,function(c){var e=o(c)+o(a);if(s.style[e]!==g)return b="-"+c+"-"+a,!0});return b}function o(a){return a.charAt(0).toUpperCase()+
a.substr(1)}function m(a,b){for(var c=0,e=a.length;c<e;c++)if(b(a[c],c))return!0;return!1}var s=h.createElement("div"),u=["webkit","moz","o","ms"],n={},f=d.support={},p=!1;f.transform3d=r(["perspectiveProperty","WebkitPerspective","MozPerspective","OPerspective","msPerspective"]);f.transform=r(["transformProperty","WebkitTransform","MozTransform","OTransform","msTransform"]);f.transition=r(["transitionProperty","WebkitTransitionProperty","MozTransitionProperty","OTransitionProperty","msTransitionProperty"]);
f.addEventListener="addEventListener"in q;f.mspointer=q.navigator.msPointerEnabled;f.cssAnimation=(f.transform3d||f.transform)&&f.transition;var t=["touch","mouse","pointer"],i={touch:"touchstart",mouse:"mousedown",pointer:"MSPointerDown"},j={touch:"touchmove",mouse:"mousemove",pointer:"MSPointerMove"},k={touch:"touchend",mouse:"mouseup",pointer:"MSPointerUp"};f.addEventListener&&(h.addEventListener("gesturestart",function(){p=!0}),h.addEventListener("gestureend",function(){p=!1}));d.prototype.init=
function(a,b){var c=this;c.element=a;if(typeof a==="string")c.element=h.querySelector(a);if(!c.element)throw Error("element not found");if(f.mspointer)c.element.style.msTouchAction="none";b=b||{};c.distance=b.distance;c.maxPoint=b.maxPoint;c.disableTouch=b.disableTouch===g?false:b.disableTouch;c.disable3d=b.disable3d===g?false:b.disable3d;c.transitionDuration=b.transitionDuration===g?"350ms":b.transitionDuration+"ms";c.currentPoint=0;c.currentX=0;c.animation=false;c.use3d=f.transform3d;if(c.disable3d===
true)c.use3d=false;f.cssAnimation?c._setStyle({transitionProperty:w("transform"),transitionTimingFunction:"cubic-bezier(0,0,0.25,1)",transitionDuration:"0ms",transform:c._getTranslate(0)}):c._setStyle({position:"relative",left:"0px"});c.refresh();t.forEach(function(a){c.element.addEventListener(i[a],c,false)});return c};d.prototype.handleEvent=function(a){switch(a.type){case i.touch:case i.mouse:case i.pointer:this._touchStart(a);break;case j.touch:case j.mouse:case j.pointer:this._touchMove(a);break;
case k.touch:case k.mouse:case k.pointer:this._touchEnd(a);break;case "click":this._click(a)}};d.prototype.refresh=function(){var a;if(this.maxPoint===g){a=this.element.childNodes;for(var b=0,c=0,e=a.length,d;c<e;c++){d=a[c];d.nodeType===1&&b++}b>0&&b--;a=b}else a=this.maxPoint;this._maxPoint=a;this._distance=this.distance===g?this.element.scrollWidth/(this._maxPoint+1):this.distance;this._maxX=-this._distance*this._maxPoint;this.moveToPoint()};d.prototype.hasNext=function(){return this.currentPoint<
this._maxPoint};d.prototype.hasPrev=function(){return this.currentPoint>0};d.prototype.toNext=function(a){this.hasNext()&&this.moveToPoint(this.currentPoint+1,a)};d.prototype.toPrev=function(a){this.hasPrev()&&this.moveToPoint(this.currentPoint-1,a)};d.prototype.moveToPoint=function(a,b){var b=b===g?this.transitionDuration:b+"ms",c=this.currentPoint;if(a===g)a=this.currentPoint;this.currentPoint=a<0?0:a>this._maxPoint?this._maxPoint:parseInt(a,10);f.cssAnimation?this._setStyle({transitionDuration:b}):
this.animation=true;this._setX(-this.currentPoint*this._distance,b);if(c!==this.currentPoint){this._triggerEvent("fsmoveend",true,false);this._triggerEvent("fspointmove",true,false)}};d.prototype._setX=function(a,b){this.currentX=a;f.cssAnimation?this.element.style[n.transform]=this._getTranslate(a):this.animation?this._animate(a,b||this.transitionDuration):this.element.style.left=a+"px"};d.prototype._touchStart=function(a){var b=this;if(!b.disableTouch&&!b._eventType&&!p){m(t,function(c){if(a.type===
i[c]){b._eventType=c;return true}});b.element.addEventListener(j[b._eventType],b,false);h.addEventListener(k[b._eventType],b,false);b._eventType==="mouse"&&a.preventDefault();f.cssAnimation?b._setStyle({transitionDuration:"0ms"}):b.animation=false;b.scrolling=true;b.moveReady=false;b.startPageX=l(a,"pageX");b.startPageY=l(a,"pageY");b.basePageX=b.startPageX;b.directionX=0;b.startTime=a.timeStamp;b._triggerEvent("fstouchstart",true,false)}};d.prototype._touchMove=function(a){if(this.scrolling&&!p){var b=
l(a,"pageX"),c=l(a,"pageY"),e;if(this.moveReady){a.preventDefault();a.stopPropagation();a=b-this.basePageX;e=this.currentX+a;if(e>=0||e<this._maxX)e=Math.round(this.currentX+a/3);this.directionX=a===0?this.directionX:a>0?-1:1;!this._triggerEvent("fstouchmove",true,true,{delta:a,direction:this.directionX})?this._touchAfter({moved:false,originalPoint:this.currentPoint,newPoint:this.currentPoint,cancelled:true}):this._setX(e)}else{e=Math.abs(b-this.startPageX);c=Math.abs(c-this.startPageY);if(e>5){a.preventDefault();
a.stopPropagation();this.moveReady=true;this.element.addEventListener("click",this,true)}else if(c>5)this.scrolling=false}this.basePageX=b}};d.prototype._touchEnd=function(){this.element.removeEventListener(j[this._eventType],this,false);h.removeEventListener(k[this._eventType],this,false);this._eventType=null;if(this.scrolling){var a=-this.currentX/this._distance,a=this.directionX>0?Math.ceil(a):this.directionX<0?Math.floor(a):Math.round(a);if(a<0)a=0;else if(a>this._maxPoint)a=this._maxPoint;this._touchAfter({moved:a!==
this.currentPoint,originalPoint:this.currentPoint,newPoint:a,cancelled:false});this.moveToPoint(a)}};d.prototype._click=function(a){a.stopPropagation();a.preventDefault()};d.prototype._touchAfter=function(a){var b=this;b.scrolling=false;b.moveReady=false;setTimeout(function(){b.element.removeEventListener("click",b,true)},200);b._triggerEvent("fstouchend",true,false,a)};d.prototype._setStyle=function(a){var b=this.element.style,c;for(c in a)v(b,c,a[c])};d.prototype._animate=function(a,b){var c=this.element,
e=+new Date,d=parseInt(c.style.left,10),f=parseInt(b,10),g=setInterval(function(){var b=new Date-e;if(b>f){clearInterval(g);b=a}else var h=b,b=-(h=h/f)*(h-2),b=b*(a-d)+d;c.style.left=b+"px"},10)};d.prototype.destroy=function(){var a=this;t.forEach(function(b){a.element.removeEventListener(i[b],a,false)})};d.prototype._getTranslate=function(a){return this.use3d?"translate3d("+a+"px, 0, 0)":"translate("+a+"px, 0)"};d.prototype._triggerEvent=function(a,b,c,d){var f=h.createEvent("Event");f.initEvent(a,
b,c);if(d)for(var g in d)f[g]=d[g];return this.element.dispatchEvent(f)};q.Flipsnap=d})(window,window.document);
