KISSY.add("mobile/app/1.0/index",function(b,h){function a(d){if(this instanceof a)a.superclass.constructor.call(this,d),this.init();else return new a(d)}var c=window.history;a.ATTRS={viewpath:{value:"index.html"},forceReload:{value:!0},page:{value:null},direction:{value:"none"},anim:{value:!0},dataload:{value:"true"},param:{value:null},pageCache:{value:!1},tapTrigger:{value:"a"},animWrapperAutoHeightSetting:{value:!0},basepath:{value:window.location.protocol+"//"+window.location.hostname+window.location.pathname.replace(/\/[^\/]+$/i,
"").replace(/\/$/,"")+"/"},initPostData:{value:null},signet:{value:{level:0,viewpath:"",hisurl:"",lastviewpath:"",forward:0,scrollTop:0}},fullRangeWidth:{value:function(){return document.body.offsetWidth}},webkitOptimize:{value:!0},positionMemory:{value:!0}};b.mix(a,{STARTUP:{},TEARDOWN:{},INCLUDEONCE:{},DESTORY:{},PAGECACHE:{},PAGESCROLL:{},STORAGE:{},APP:null,AndroidHis:{},includeOnce:function(d){var a=this.APP.get("viewpath");b.isFunction(this.INCLUDEONCE[a])||(this.INCLUDEONCE[a]=d,d.call(this.APP,
this.APP))},destory:function(d){var a=this.APP.get("viewpath");b.isFunction(this.DESTORY[a])||(this.DESTORY[a]=d)},startup:function(d){var a=this.APP.get("viewpath");b.isFunction(this.STARTUP[a])||(this.STARTUP[a]=d)},teardown:function(a){var e=this.APP.get("viewpath");b.isFunction(this.TEARDOWN[e])||(this.TEARDOWN[e]=a)}});b.extend(a,b.Base,{init:function(){this.MS=this.constructor;b.UA.opera&&0<b.UA.opera&&this.set("animWrapperAutoHeightSetting",!0);this.slide=new h("MS",{autoSlide:!1,effect:this.get("anim")?
"hSlide":"none",touchmove:!1,adaptive_fixed_width:!0,contentClass:"MS-con",speed:450,pannelClass:"MS-pal",animWrapperAutoHeightSetting:this.get("animWrapperAutoHeightSetting"),webkitOptimize:this.get("webkitOptimize"),adaptive_width:this.get("fullRangeWidth")});this.positionTimmer=null;this.slide.addHeightTimmer();this.bindEvent();this.initLoad();a.APP=this;return this},callDestory:function(){var a=this.MS.DESTORY[this.get("signet").lastviewpath];b.isFunction(a)&&a.call(this,this);return this},initPageStorage:function(){var a=
this.get("viewpath");if(!b.isObject(this.MS.STORAGE[a])){var e=function(){};b.augment(e,b.Base.Attribute,b.EventTarget);this.MS.STORAGE[a]=new e}},callStartup:function(a){b.isUndefined(a)&&(a=this.get("viewpath"));var e=this.MS.STARTUP[a],c=this.get("param");this.set("param",null);this.set("storage",this.MS.STORAGE[a]||{});b.isFunction(e)&&e.call(this,c);return this},callTeardown:function(a){b.isUndefined(a)&&(a=this.get("viewpath"));if(""!==a){var e=this.MS.TEARDOWN[a];this.rememberPosition(a);return b.isFunction(e)?
e.call(this,this):!0}},rememberPosition:function(a){this.MS.PAGESCROLL[a]=b.DOM.scrollTop()},recallPosition:function(){if(this.get("positionMemory")){var a=this.MS.PAGESCROLL[this.get("viewpath")];a&&(window.scrollTo(0,a),0===b.DOM.scrollTop()&&setTimeout(function(){window.scrollTo(0,a)},200))}},initLoad:function(){b.isUndefined(b.getHash().viewpath)||this.set("viewpath",b.getHash().viewpath);b.isNull(this.get("initPostData"))||(this.__post=this.get("initPostData"));this._go(this.get("viewpath"),
"none");var a=this.formatUrlTail(this.get("viewpath"),b.getHash()),e={level:0,viewpath:this.get("viewpath"),hisurl:a,forward:0,lastviewpath:"",scrollTop:b.DOM.scrollTop()};this.set("signet",e);c.replaceState(e,"",a);this.set("viewpath",b.getHash().viewpath)},rollback:function(){var a=this.formatUrlTail(this.get("viewpath"),b.getHash()),e={level:0,viewpath:this.get("viewpath"),hisurl:a,forward:0,lastviewpath:"",scrollTop:b.DOM.scrollTop()};this.set("signet",e);c.replaceState(e,"",a);this.set("viewpath",
b.getHash().viewpath)},loading:function(){var a=this,e=b.one("#MS-loading"),e=e?e:b.Node('<div id="MS-loading" style="display:none"><img src="http://img04.taobaocdn.com/tps/i4/T1aIsKXmReXXa679Pe-40-40.gif" /></div>').appendTo("body");e.one("img").css({"margin-top":"5px"});e.css({display:"none",position:"fixed",height:"50px",width:"50px",top:"50%",left:"50%","margin-top":"-25px","margin-left":"-25px","border-radius":"6px","text-align":"center","background-color":"white",opacity:0.7});a.loadingTimer=
setTimeout(function(){e.css({display:"block"});a.loadingTimer=null},350);return a},closeLoading:function(){this.loadingTimer&&clearTimeout(this.loadingTimer);var a=b.one("#MS-loading");a&&a.css({display:"none"});return this},getUrlPrefix:function(){var a=window.location;return a.pathname.replace(/\/.+\//i,"").replace("/","")+a.search},formatUrlTail:function(a,e){b.isUndefined(e)&&(e="");b.isString(e)&&(e=b.unparam(e));var c=b.setHash(b.merge(e,{viewpath:a}));return this.getUrlPrefix()+c.replace(/^.+#/i,
"#")},setRouteHash:function(a,e){this.set("viewpath",a);b.isUndefined(e)&&(e="");b.isString(e)&&(e=b.unparam(e));var f=this.formatUrlTail(a,b.getHash()),f={level:this.get("signet").level+1,viewpath:a,hisurl:b.setHash(f,e),forward:1,lastviewpath:a,scrollTop:b.DOM.scrollTop()},g=window.location,g=g.protocol+"//"+g.hostname+g.pathname+g.search,g=b.setHash(g,b.merge({viewpath:a},e));b.UA.android&&4.3>b.UA.android?window.location.href=g:(this.doHashChange(a,e),c.replaceState(f,"",g))},doHashChange:function(a,
c){var f=b.setHash(b.merge({stamp:b.now(),viewpath:a},c)).match(/#.*$/i)[0];window.location.hash=f},bindEvent:function(){var a=this;if(b.UA.android&&4.3>b.UA.android){var e=b.getHash().viewpath?b.getHash().viewpath:a.get("viewpath");a.MS.AndroidHis[e]=1}a.slide.con.delegate("click",a.get("tapTrigger"),function(c){var e=b.one(c.currentTarget);if(!b.isUndefined(e.attr("target"))&&""!==e.attr("target")||/^javascript:/i.test(e.attr("href")))return"top"==e.attr("target")&&(window.location.href=e.attr("href"),
c.preventDefault()),!0;a.__clickEvent=!0;var h=e.attr("href"),e=e.attr("data-param");if(""===h)return!0;a.setRouteHash(h,e);c.preventDefault()});b.Event.on(window,"hashchange",function(){var e=a.get("signet"),g=b.getHash().viewpath;a.set("viewpath",b.getHash().viewpath);var h=!1,h=a.__clickEvent&&!0===a.__clickEvent?!0:!1;delete a.__clickEvent;b.isUndefined(g)||(a.formatUrlTail(g,b.getHash()),b.UA.android&&4.3>b.UA.android?a._androidHistoryMan(h):b.isUndefined(c.state)||b.isUndefined(c.state.level)?
(a._go(g,"none"),a.recordSignet(0,g)):0===a.get("signet").forward&&0<c.state.forward?(a.next(g),a.recordSignet(1,g)):c.state.level>e.level?0<a.get("signet").forward&&0>c.state.forward?(a.prev(g),a.recordSignet(1,g,-1)):(a.next(g),a.recordSignet(1,g)):(0<a.get("signet").forward&&0>c.state.forward?a.prev():0>a.get("signet").forward&&0<c.state.forward?a.next(g,function(){a.callDestory();a.slide.remove(a.slide.length-2)}):a.prev(function(){a.recallPosition()}),a.recordSignet(-1,g,c.state.forward)))})},
recordSignet:function(a,e,c){b.isUndefined(a)&&(a=0,e=b.getHash().viewpath,c=1);b.isUndefined(e)&&(e=b.getHash().viewpath,c=1);b.isUndefined(c)&&(c=1);var g=this.get("signet").level,h=this.formatUrlTail(e,b.getHash()),a={level:g+a,viewpath:e,hisurl:h,forward:c,lastviewpath:this.get("signet").viewpath,scrollTop:b.DOM.scrollTop()};this.set("signet",a);return a},destory:function(){},_go:function(a,c,f){if(!1===this.callTeardown(this.get("signet").viewpath))return this.rollback(),this;b.isUndefined(c)&&
(c="next",f=function(){});b.isFunction(c)&&(f=c,c="next");b.isUndefined(f)&&(f=function(){});this.loadData(a,c,f)},postback:function(a){this.__post=a.data;b.isString(a.path)?this.back(a.path,a.data,a.callback):this.back(a.data,a.callback)},postforward:function(a){this.__post=a.data;b.isString(a.path)?this.forward(a.path,a.data,a.callback):this.forward(a.data,a.callback)},back:function(a,e,f){b.isUndefined(a)&&(a=void 0,e={},f=function(){});b.isUndefined(e)&&(e={},f=function(){});b.isFunction(e)&&
(f=e,e={});b.isObject(a)&&(e=a,f=function(){},a=void 0);b.isObject(e)&&b.isUndefined(f)&&(f=function(){});b.isString(e)&&(e=b.unparam(e));this.set("param",b.merge(e,{from:this.get("signet").viewpath}));if(b.isString(a)){this.prev.apply(this,arguments);var g=this.recordSignet(1,a,-1);c.pushState(g,"",b.setHash(g.hisurl,e))}else c.back();this.set("viewpath",b.getHash().viewpath);return this},forward:function(a,e,f){b.isUndefined(e)&&(e={},f=function(){});b.isFunction(e)&&(f=e,e={});b.isObject(e)&&b.isUndefined(f)&&
(f=function(){});b.isString(e)&&(e=b.unparam(e));this.set("param",b.merge(e,{from:this.get("signet").viewpath}));this.next.apply(this,arguments);var g=this.recordSignet(1,a);c.pushState(g,"",b.setHash(g.hisurl,e));this.set("viewpath",b.getHash().viewpath);return this},_androidHistoryMan:function(a,c){var f=this;b.isUndefined(c)&&(c=f.get("viewpath"));if(a||!(c in f.MS.AndroidHis))f.next(c),f.recordSignet(1,c);else{f.prev(c,function(){f.recallPosition()});f.recordSignet(1,c,-1);for(var g in f.MS.AndroidHis)1==
f.MS.AndroidHis[g]&&delete f.MS.AndroidHis[g]}for(var h in f.MS.AndroidHis)f.MS.AndroidHis[h]=null;f.MS.AndroidHis[c]=1},next:function(a,c){var f=this;b.isFunction(a)&&(c=a,a=void 0);b.isUndefined(c)&&(c=function(){});if(b.isUndefined(a)){if(!1===f.callTeardown(f.get("signet").viewpath))return f.rollback(),this;f.slide.removeHeightTimmer();f.get("animWrapperAutoHeightSetting")&&window.scrollTo(0,0);f.slide.next(function(){f.slide.addHeightTimmer();b.isFunction(c)&&c.call(f.slide,f.slide);f.get("forceReload")&&
f.slide.remove(f.slide.length-2)});f.set("page",f.slide.getCurrentPannel());setTimeout(function(){f.callStartup()},0)}else f._go(a,"next",c)},prev:function(a,c){var f=this;b.isFunction(a)&&(c=a,a=void 0);b.isUndefined(c)&&(c=function(){});!b.isString(a)&&f.get("forceReload")&&(a=f.get("viewpath"));if(b.isUndefined(a)){if(!1===f.callTeardown(f.get("signet").viewpath))return f.rollback(),this;f.slide.removeHeightTimmer();f.slide.previous(function(){f.slide.addHeightTimmer();f.callDestory();this.removeLast();
b.isFunction(c)&&c.call(f.slide,f.slide)});f.set("page",f.slide.getCurrentPannel());setTimeout(function(){f.callStartup()},0)}else f._go(a,"prev",c)},getAjaxPath:function(a){return this.get("basepath")+a},loadData:function(a,c,f){var g=this;b.isUndefined(c)&&(c="next",f=function(){});b.isFunction(c)&&(f=c,c="next");b.isUndefined(f)&&(f=function(){});var h=function(a){g.closeLoading();var d=b.Node('<div class="MS-pal">'+a+"</div>");g.set("page",d);switch(c){case "prev":g.slide.add(d,g.slide.currentTab);
g.slide.relocateCurrentTab(g.slide.currentTab+1);b.execScript(a);setTimeout(function(){g.initPageStorage();g.callStartup()},0);setTimeout(function(){g.slide.removeHeightTimmer();g.slide.previous(function(){g.slide.addHeightTimmer();g.callDestory();b.isFunction(f)&&f.call(g.slide,g.slide);this.removeLast()})},150);break;case "next":g._fixScrollTopBefore(d);g.slide.add(d);b.execScript(a);setTimeout(function(){g.initPageStorage();g.callStartup()},0);setTimeout(function(){g.slide.removeHeightTimmer();
g.get("animWrapperAutoHeightSetting")&&window.scrollTo(0,0);g.slide.next(function(){g.callDestory();b.isFunction(f)&&f.call(g.slide,g.slide);g.get("forceReload")&&g.slide.remove(g.slide.length-2);g._fixScrollTopAfter(d)})},150);break;case "none":g.slide.add(d,g.slide.currentTab);g.callDestory();b.execScript(a);setTimeout(function(){g.initPageStorage();g.callStartup()},0);f.call(g.slide,g.slide);g.slide.removeLast()}},i=function(c){c=c.replace(/.*<\!--kdk{{--\>/ig,"").replace(/<\!--kdk}}--\>*/ig,"");
g.MS.PAGECACHE[a]=c;h(c)},j=g.getAjaxPath(a);g.loading();g.__post?(b.io.post(j,g.__post,i),delete g.__post):g.get("pageCache")&&!b.isUndefined(g.MS.PAGECACHE[a])?h(g.MS.PAGECACHE[a]):b.io.get(j,i)},_fixScrollTopBefore:function(a){if(!this.get("animWrapperAutoHeightSetting")){var c=b.DOM.scrollTop();a.css({"margin-top":c+"px"})}},_fixScrollTopAfter:function(a){var c=this;if(!c.get("animWrapperAutoHeightSetting")){var f=a.parent(),g=function(){a.appendTo(f).css({"margin-top":0,position:"relative",left:0});
c.slide.addHeightTimmer()};a.appendTo("body").css({"margin-top":0,position:"fixed",top:0,left:c.slide.con.offset().left+"px"});b.UA.opera&&0<b.UA.opera?(window.scrollTo(0,0),g()):b.Anim(window,{scrollTop:0},0.1,"easeBoth",function(){g()}).run()}}});return a},{requires:["./slide","base","ajax"]});
KISSY.add("mobile/app/1.0/kissy2yui",function(b){b.augment(b.Node,{_delegate:function(){b.isFunction(arguments[1])?this.delegate(arguments[0],arguments[2],arguments[1]):this.delegate.apply(this,arguments);return this},indexOf:function(h){if(b.isUndefined(h))return null;h[0]&&(h=h[0]);var a=0;this.each(function(c,d){c[0]===h&&(a=d)});return a},size:function(){return this.length},set:function(b,a){"innerHTML"===b?this.html(a):this.attr(b,a);return this},get:function(b){var a=this,c={innerHTML:function(){return a.html()},
region:function(){return{height:a.height(),width:a.width()}}};if(b in c)return c[b]()},appendChild:function(){this.append.apply(this,arguments);return this},setStyle:function(b,a){this.css.apply(this,arguments);return this},setStyles:function(b){this.css.apply(this,arguments);return this},cloneNode:function(){return this.clone.apply(this,arguments)}});b.Node.create=function(h){return b.Node(h)}},{requires:["node","event"]});
KISSY.add("mobile/app/1.0/slide",function(b){var h=function(){if(!(this instanceof h))throw Error('please use "new Slide()"');this.init.apply(this,arguments)};h.plug=function(){};b.augment(h,b.Event.Target,{init:function(a,c){if(b.isObject(a))this.con=a;else if(/^#/i.test(a))this.con=b.one(a);else if(b.one("#"+a))this.con=b.one("#"+a);else if(b.one(a))this.con=b.one(a);else throw Error("Slide Container Hooker not found");this.buildParam(c);this.buildHTML();this.bindEvent();this.fire("ready",{index:0,
navnode:this.tabs.item(0),pannelnode:this.pannels.item(0)});if(this.reverse){var d;d=this.previous;this.previous=this.next;this.next=d}if(this.carousel)for(d=0;d<this.colspan;d++)this.fix_for_transition_when_carousel(2*d);this.fixSlideSize();this.layerSlide&&this.initLayer();return this},setWrapperSize:function(a){var c=this;b.isUndefined(a)&&(a=0);c.pannels=c.con.all("."+c.contentClass+" div."+c.pannelClass);c.length=c.pannels.length;({none:function(){},vSlide:function(){var b=c.animcon.get("region");
c.animwrap.setStyles({height:(c.length+a)*b.height/c.colspan+"px"})},hSlide:function(){var b=c.animcon.get("region");c.animwrap.setStyles({width:(c.length+a)*b.width/c.colspan+"px"})},fade:function(){}})[c.effect]();b.isUndefined(a)||c.relocateCurrentTab();return this},add:function(a,c){var d=this;if(b.isUndefined(c)||c>d.length)c=d.length;b.isString(a)&&(a=b.one(a));d.transitions&&a.css({visibility:"hidden"});c==d.length?(setTimeout(function(){d.setWrapperSize(1)},0),a.insertAfter(d.pannels[c-1])):
a.insertBefore(d.pannels[c]);d.setWrapperSize();d.fixSlideSize(d.currentTab);d.transitions&&a.css({visibility:""});return this},remove:function(a){if(1!==this.length)return a<=this.currentTab&&(this.currentTab--,this.length--),this.transitions&&this.con.css({display:"none"}),b.one(this.pannels[a]).remove(),this.setWrapperSize(),this.transitions&&this.con.css({display:"block"}),this.fixSlideSize(this.currentTab),this},removeLast:function(){this.remove(this.length-1);return this},renderLazyData:function(a){a.setStyle("display",
"none");if("1"!=a.attr("lazy-data")){a.attr("lazy-data","1");b.stamp(d);var c=a.get("innerHTML").replace(/&lt;/ig,"<").replace(/&gt;/ig,">"),d=b.Node.create("<div>"+c+"</div>");b.DOM.insertBefore(d,a);b.execScript(c)}},buildWrap:function(){this.animwrap=b.Node.create('<div style="position:absolute;"></div>');this.animwrap.set("innerHTML",this.animcon.get("innerHTML"));this.animcon.set("innerHTML","");this.animcon.appendChild(this.animwrap);this.pannels=this.con.all("."+this.contentClass+" div."+this.pannelClass);
return this},doEffectInit:function(){var a=this;({none:function(){a.pannels=a.con.all("."+a.contentClass+" div."+a.pannelClass);a.pannels.setStyles({display:"none"});a.pannels.item(a.defaultTab).setStyles({display:"block"})},vSlide:function(){a.buildWrap();var c=a.animcon.get("region");a.pannels.setStyles({"float":"none",overflow:"hidden"});a.animwrap.setStyles({height:a.length*c.height/a.colspan+"px",overflow:"hidden",top:-1*a.defaultTab*c.height+"px"})},hSlide:function(){a.buildWrap();var c=a.animcon.get("region");
a.pannels.setStyles({"float":"left",overflow:"hidden"});a.animwrap.setStyles({width:a.length*c.width/a.colspan+"px",overflow:"hidden",left:-1*a.defaultTab*c.width+"px"})},fade:function(){a.pannels=a.con.all("."+a.contentClass+" div."+a.pannelClass);a.pannels.setStyles({position:"absolute",zIndex:0});a.pannels.each(function(c,b){b==a.defaultTab?c.setStyles({opacity:1,display:"block"}):c.setStyles({opacity:0,diaplay:"none"})})}})[a.effect]();return this},buildHTML:function(){var a=this.con;this.tabs=
a.all("."+this.navClass+" "+this.triggerSelector);this.length=a.all("."+this.contentClass+" ."+this.pannelClass).size();a.one("."+this.navClass)||b.Node('<ul class="'+this.navClass+'" style="display:none"></ul>').appendTo(this.con);if(0===this.tabs.size()){for(var c=a.all("."+this.navClass),d="",e=0;e<this.length;e++){var f="";0===e&&(f=this.selectedClass);d+='<li class="'+f+'"><a href="javascript:void(0);">'+(e+1)+"</a></li>"}c.set("innerHTML",d)}this.tabs=a.all("."+this.navClass+" "+this.triggerSelector);
this.animcon=a.one("."+this.contentClass);this.animwrap=null;this.doEffectInit();this.fixSlideSize(this.currentTab);this.hightlightNav(this.getWrappedIndex(this.currentTab));!0===this.autoSlide&&this.play();return this},getCurrentPannel:function(){return b.one(this.pannels[this.currentTab])},renderWidth:function(){var a=this.animcon.get("region").width;"hSlide"==this.effect&&(a/=this.colspan);this.pannels.setStyles({width:a+"px"});return this},renderHeight:function(){var a=this.animcon.get("region").height;
"vSlide"==this.effect&&(a/=this.colspan);this.pannels.setStyles({height:a+"px"});return this},relocateCurrentTab:function(a){b.isUndefined(a)&&(a=this.currentTab);if("hSlide"==this.effect)return this.transitions?this.animwrap.setStyles({"-webkit-transition-duration":"0s","-webkit-transform":"translate3d("+-1*a*this.animcon.get("region").width+"px,0,0)","-webkit-backface-visibility":"hidden"}):this.animwrap.setStyles({left:-1*a*this.animcon.get("region").width}),this.currentTab=a,this},fixSlideSize:function(a){this.adaptive_fixed_width&&
this.renderWidth();this.adaptive_fixed_height&&this.renderHeight();this.adaptive_fixed_size&&this.renderHeight().renderWidth();this.resetSlideSize(a);return this},removeHeightTimmer:function(){b.isNull(this.heightTimmer)||(clearInterval(this.heightTimmer),this.heightTimmer=null)},addHeightTimmer:function(){var a=this;b.isNull(a.heightTimmer)||(clearInterval(a.heightTimmer),a.heightTimmer=null);var c=function(){a.effect=="hSlide"&&a.animcon.setStyles({height:a.pannels.item(a.currentTab).get("region").height+
"px"})};a.heightTimmer=setInterval(c,100);c()},resetSlideSize:function(a){var c,b;if("undefined"==typeof a||null===a)a=this.currentTab;if(!("hSlide"!=this.effect&&"vSlide"!=this.effect))return"hSlide"==this.effect&&(c=this.adaptive_width?this.adaptive_width():this.animcon.get("region").width,b=this.pannels.item(a).get("region").height,c/=this.colspan,this.pannels.setStyles({width:c+"px",display:"block"}),this.animcon.setStyles({width:c*this.colspan+"px",overflow:"hidden"}),this.animWrapperAutoHeightSetting&&
this.animcon.setStyles({height:b+"px"})),"vSlide"==this.effect&&(c=this.pannels.item(a).get("region").width,b=this.adaptive_height?this.adaptive_height():this.animcon.get("region").height,b/=this.colspan,this.pannels.setStyles({height:b*this.colspan+"px",display:"block"}),this.animcon.setStyles({height:b*this.colspan+"px",overflow:"hidden"}),this.animWrapperAutoHeightSetting&&this.animcon.setStyles({width:c+"px"})),this},getWrappedIndex:function(a){var c=0;return c=this.carousel?a<this.colspan?this.length-
3*this.colspan+a:a>=this.length-this.colspan?a-(this.length-this.colspan):a-this.colspan:a},bindEvent:function(){var a=this;b.inArray(a.eventType,["click","mouseover","mouseenter"])&&a.con._delegate(a.eventType,function(c){c.halt();c=Number(a.tabs.indexOf(c.currentTarget));a.carousel&&(c=(c+1)%a.length);a.go(c);a.autoSlide&&a.stop().play()},"."+a.navClass+" "+a.triggerSelector);a.hoverStop&&(a.con._delegate("mouseover",function(){a.autoSlide&&a.stop()},"."+a.contentClass+" div."+a.pannelClass),a.con._delegate("mouseout",
function(){a.autoSlide&&a.play()},"."+a.contentClass+" div."+a.pannelClass));b.Event.on("resize",function(){a.fixSlideSize(a.currentTab);a.relocateCurrentTab()},window);a.on("beforeSwitch",function(){if(this.layerSlide&&this.isAming())return false});if("ontouchstart"in document.documentElement){if(!a.touchmove)return this;a.con._delegate("touchstart",function(c){a.stop();a.touching=true;a.is_last()&&a.carousel&&a.fix_next_carousel();a.is_first()&&a.carousel&&a.fix_pre_carousel();a.startX=c.changedTouches[0].clientX;
a.startY=c.changedTouches[0].clientY;a.animwrap.setStyles({"-webkit-transition-duration":"0s"});a.startT=Number(new Date)},"."+a.contentClass);a.con._delegate("touchend",function(c){a.touching=false;var b=c.changedTouches[0].clientX,c=Number(a.animcon.get("region").width);a.deltaX=Math.abs(b-a.startX);var e=Math.abs(b)<Math.abs(a.startX),b=!e,b=a.carousel?false:a.is_last()&&e||a.is_first()&&b,f=function(){a.animwrap.setStyles({"-webkit-transition-duration":Number(a.speed)/2+"s","-webkit-transform":"translate3d("+
-1*a.currentTab*a.animcon.get("region").width/a.colspan+"px,0,0)"})},g=function(){var b=a.animcon.get("region").width/a.colspan,b=parseInt((a.deltaX-b/2)/b,10);if(e){if(b>=1&&a.length>2){a.currentTab=a.currentTab+b;if(a.currentTab>=a.length-1)a.currentTab=a.length-2}a.next()}else{if(b>=1&&a.length>2)a.currentTab=a.currentTab-b<=0?1:a.currentTab+-1*b;a.previous()}};if(a.touchmove&&a.deltaX<30)f();else{!b&&(a.touchmove&&a.deltaX>c/3||!a.touchmove&&a.carousel||!a.carousel&&a.touchmove&&a.effect=="hSlide"||
!a.touchmove&&!a.carousel||Number(new Date)-a.startT<550)?g():f();a.autoSlide&&a.play()}},"."+a.contentClass);a.touchmove&&(a.con._delegate("touchmove",function(b){if(!(b.touches.length>1)){a.deltaX=b.touches[0].clientX-a.startX;var d=a.is_last()&&a.deltaX<0||a.is_first()&&a.deltaX>0;if(!a.carousel&&a.effect=="hSlide"&&d)a.deltaX=a.deltaX/3;a.isScrolling=Math.abs(a.deltaX)<Math.abs(b.touches[0].clientY-a.startY)?true:false;if(!a.isScrolling){b.halt();a.stop();b=Number(a.animcon.get("region").width/
a.colspan);a.animwrap.setStyles({"-webkit-transition-duration":"0s","-webkit-transform":"translate3d("+(a.deltaX-a.currentTab*b)+"px,0,0)"})}}},"."+a.contentClass),a.animwrap.on("webkitTransitionEnd",function(){}))}return this},initLayer:function(){var a=this;if(!("ontouchstart"in document.documentElement||0<b.UA.ie&&9>b.UA.ie)){var c="durationin,easingin,durationout,easingout,delayin,delayout,slideindirection,slideoutdirection,offsetin,offsetout,alpha,easeInStrong,easeOutStrong,easeBothStrong,easeNone,easeIn,easeOut,easeBoth,elasticIn,elasticOut,elasticBoth,backIn,backOut,backBoth,bounceIn,bounceOut,bounceBoth,left,top,right,bottom".split(","),
d={durationin:1E3,easingin:"easeIn",durationout:1E3,easingout:"easeOut",delayin:300,delayout:300,slideindirection:"right",slideoutdirection:"left",alpha:!0,offsetin:50,offsetout:50},e=function(a){var e=this,h=a.attr("rel").replace(/"'/ig,"").replace(RegExp("("+c.join("|")+")","ig"),'"$1"'),i=b.JSON.parse("{"+h+"}");b.each(d,function(a,b){var c=i[b];e[b]=void 0===c||null===c?a:c});this.el=a;this.left=Number(a.css("left").replace("px",""));this.top=Number(a.css("top").replace("px",""));this.animIn=
function(){var a=this,c=a.offsetin,d=a.slideindirection;({left:function(){a.el.css({left:a.left-c})},top:function(){a.el.css({top:a.top-c})},right:function(){a.el.css({left:a.left+c})},bottom:function(){a.el.css({top:a.top+c})}})[d]();setTimeout(function(){var c={};b.mix(c,{left:{left:a.left},top:{top:a.top},bottom:{top:a.top},right:{left:a.left}}[d]);a.alpha&&b.mix(c,{opacity:1});b.Anim(a.el,c,a.durationin/1E3,a.easingin,function(){}).run()},a.delayin);a.alpha&&a.el.css({opacity:0})};this.animOut=
function(){}};a.sublayers=[];a.pannels.each(function(b,c){("vSlide"==a.effect||"hSlide"==a.effect)&&b.css({position:"relative"});0===b.all('[alt="sublayer"]').length?a.sublayers[c]=[]:(void 0===a.sublayers[c]&&(a.sublayers[c]=[]),b.all('[alt="sublayer"]').each(function(b){a.sublayers[c].push(new e(b))}))});a.on("beforeSwitch",function(b){if(b.index===a.currentTab)return!1;a.subLayerRunin(b.index)});a.on("beforeTailSwitch",function(b){a.subLayerRunout(b.index)})}},subLayerRunin:function(a){b.each(this.sublayers[a],
function(a){a.animIn()})},subLayerRunout:function(a){b.each(this.sublayers[a],function(a){a.animOut()})},buildParam:function(a){var c=this;if(void 0===a||null===a)a={};b.each({autoSlide:!1,speed:500,timeout:3E3,effect:"none",eventType:"click",easing:"easeBoth",hoverStop:!0,selectedClass:"selected",conClass:"t-slide",navClass:"tab-nav",triggerSelector:"li",contentClass:"tab-content",pannelClass:"tab-pannel",carousel:!1,reverse:!1,touchmove:!1,adaptive_fixed_width:!1,adaptive_fixed_height:!1,adaptive_fixed_size:!1,
adaptive_width:!1,adaptive_height:!1,defaultTab:0,layerSlide:!1,layerClass:"tab-animlayer",colspan:1,animWrapperAutoHeightSetting:!0,webkitOptimize:!0},function(b,e){var f=a[e];c[e]=void 0===f||null===f?b:f});b.mix(c,{tabs:[],animcon:null,pannels:[],timmer:null,touching:!1});c.speed/=1E3;0!==c.defaultTab&&(c.defaultTab=Number(c.defaultTab)-1);c.carousel&&(c.defaultTab=c.colspan,c.effect="hSlide");c.currentTab=c.defaultTab;c.transitions="webkitTransition"in document.body.style&&c.webkitOptimize;return c},
fix_for_transition_when_carousel:function(a){"undefined"==typeof a&&(a=0);var b=this.con;this.animcon=this.con.one("."+this.contentClass);this.animwrap=this.animcon.one("div");this.pannels=b.all("."+this.contentClass+" div."+this.pannelClass);if("hSlide"==this.effect){var d=Number(this.animcon.get("region").width/this.colspan);this.animcon.get("region");this.animwrap.setStyle("width",this.pannels.size()*d+2*d);var e=this.pannels.item(a).cloneNode(!0),f=this.pannels.item(this.pannels.size()-1-a).cloneNode(!0);
this.animwrap.append(e);this.animwrap.prepend(f);this.transitions?this.animwrap.setStyles({"-webkit-transition-duration":"0s","-webkit-transform":"translate3d("+-1*d*(a/2+1)+"px,0,0)","-webkit-backface-visibility":"hidden",left:"0"}):this.animwrap.setStyle("left",-1*d*(a/2+1))}this.pannels=b.all("."+this.contentClass+" div."+this.pannelClass);this.length=this.pannels.size();return this},isAming:function(){return this.anim?this.anim.isRunning():!1},previous:function(a){try{if(this.isAming()&&this.carousel)return this}catch(b){}var d=
this.currentTab+this.length-1-(this.colspan-1);d>=this.length-this.colspan+1&&(d%=this.length-this.colspan+1);if(this.carousel&&this.is_first())return this.fix_pre_carousel(),this.previous.call(this),this;this.go(d,a);return this},is_last:function(){return this.currentTab==this.length-(this.colspan-1)-1?!0:!1},is_first:function(){return 0===this.currentTab?!0:!1},next:function(a){try{if(this.isAming()&&this.carousel)return this}catch(b){}var d=this.currentTab+1;d>=this.length-this.colspan+1&&(d%=
this.length-this.colspan+1);if(this.carousel&&this.is_last())return this.fix_next_carousel(),this.next.call(this),this;this.go(d,a);return this},fix_next_carousel:function(){this.currentTab=this.colspan;var a=this.con;"none"!=this.effect&&(this.pannels=a.all("."+this.contentClass+" div."+this.pannelClass));a="-"+Number(this.animcon.get("region").width).toString()+"px";"hSlide"==this.effect&&(this.transitions?this.animwrap.setStyles({"-webkit-transition-duration":"0s","-webkit-transform":"translate3d("+
a+",0,0)"}):this.animwrap.setStyle("left",a))},fix_pre_carousel:function(){this.currentTab=this.length-1-2*this.colspan+1;var a=this.con;"none"!=this.effect&&(this.pannels=a.all("."+this.contentClass+" div."+this.pannelClass));a="-"+(Number(this.animcon.get("region").width/this.colspan)*this.currentTab).toString()+"px";"hSlide"==this.effect&&(this.transitions?this.animwrap.setStyles({"-webkit-transition-duration":"0s","-webkit-transform":"translate3d("+a+",0,0)"}):this.animwrap.setStyle("left",a))},
hightlightNav:function(a){if(this.carousel&&1<this.colspan)return this;this.tabs.item(a)&&(this.tabs.removeClass(this.selectedClass),this.tabs.item(a).addClass(this.selectedClass));return this},switch_to:function(a,c){var d=this,e=function(){b.isFunction(c)&&c.apply(d,d);d.fire("afterSwitch",{index:d.currentTab,navnode:d.tabs.item(d.getWrappedIndex(d.currentTab)),pannelnode:d.pannels.item(d.currentTab)})};d.fire("beforeTailSwitch",{index:d.currentTab,navnode:d.tabs.item(d.getWrappedIndex(d.currentTab)),
pannelnode:d.pannels.item(d.currentTab)});d.hightlightNav(d.getWrappedIndex(a));d.fixSlideSize(a);d.autoSlide&&d.stop().play();a>=d.length&&(a%=d.length);if(a==d.currentTab)return this;if(d.anim)try{d.anim.stop(),d.anim=null}catch(f){}({none:function(a){d.pannels.setStyles({display:"none"});d.pannels.item(a).setStyles({display:"block"});e()},vSlide:function(a){d.transitions?(d.animwrap.setStyles({"-webkit-transition-duration":d.speed+"s","-webkit-transform":"translate3d(0,"+-1*a*d.animcon.get("region").height/
d.colspan+"px,0)","-webkit-backface-visibility":"hidden"}),d.anim=b.Anim(d.animwrap,{opacity:1},d.speed,d.easing,function(){e()})):d.anim=b.Anim(d.animwrap,{top:-1*a*d.animcon.get("region").height/d.colspan},d.speed,d.easing,function(){e()});d.anim.run()},hSlide:function(a){d.transitions?(d.animwrap.setStyles({"-webkit-transition-duration":d.speed+"s","-webkit-transform":"translate3d("+-1*a*d.animcon.get("region").width/d.colspan+"px,0,0)","-webkit-backface-visibility":"hidden"}),d.anim=b.Anim(d.animwrap,
{opacity:1},d.speed,d.easing,function(){e()})):d.anim=b.Anim(d.animwrap,{left:-1*a*d.animcon.get("region").width/d.colspan},d.speed,d.easing,function(){e()});d.anim.run()},fade:function(a){var c=d.currentTab;d.anim=b.Anim(d.pannels.item(a),{opacity:1},d.speed,d.easing,function(){d.pannels.item(c).setStyle("zIndex",0);d.pannels.item(a).setStyle("zIndex",1);d.pannels.item(c).setStyle("opacity",0);d.pannels.item(c).setStyles({display:"none"});e()});d.pannels.item(a).setStyles({display:"block"});d.pannels.item(a).setStyle("opacity",
0);d.pannels.item(c).setStyle("zIndex",1);d.pannels.item(a).setStyle("zIndex",2);d.anim.run()}})[d.effect](a);d.currentTab=a;d.fire("switch",{index:a,navnode:d.tabs.item(d.getWrappedIndex(a)),pannelnode:d.pannels.item(a)});var g=d.pannels.item(a).all(".data-lazyload");g&&g.each(function(a){d.renderLazyData(a)})},go:function(a,b){!1!==this.fire("beforeSwitch",{index:a,navnode:this.tabs.item(a),pannelnode:this.pannels.item(a)})&&(a+this.colspan>this.pannels.size()&&(a=this.pannels.size()-this.colspan),
this.switch_to(a,b));return this},play:function(){var a=this;null!==a.timer&&clearTimeout(a.timer);a.timer=setTimeout(function(){a.next().play()},Number(a.timeout));return this},stop:function(){clearTimeout(this.timer);this.timer=null;return this}});return h},{requires:["node","event","json","./slide-util","./kissy2yui"]});
KISSY.add("mobile/app/1.0/util",function(b){b.mix(b,{setHash:function(b,a){var c,d;"object"==typeof b?(c=window.location.href,a=b):c=b;0>c.indexOf("#")&&(c+="#");var e=this.getHash(c);for(d in a)e[d]=a[d];c=c.split("#")[0]+"#";for(d in e)c+=d+"="+e[d]+"&";return c=c.substr(0,c.length-1)},getHash:function(h){h=h||window.location.href;if(0>h.indexOf("#"))return{};h=h.split("#")[1];if(""===h)return{};"&"==h[h.length-1]&&(h=h.substr(0,h.length-1));h=h.replace(/"/ig,"'");h=h.replace(/=/ig,'":"');h=h.replace(/&/ig,
'","');return b.JSON.parse('{"'+(h+'"')+"}")},_globalEval:function(b){if(b&&/\S/.test(b)){var a=document.getElementsByTagName("head")[0]||document.getElementsByTagName("body")[0],c=document.createElement("script");c.text=b;a.insertBefore(c,a.firstChild);setTimeout(function(){a.removeChild(c)},1)}},execScript:function(h){var a=RegExp(/<script([^>]*)>([^<]*(?:(?!<\/script>)<[^<]*)*)<\/script>/ig),c=b.one("head").getDOMNode(),d,e,f,g,k,i=/\ssrc=(['"])(.*?)\1/i,j=/\scharset=(['"])(.*?)\1/i;for(a.lastIndex=
0;d=a.exec(h);)if((f=(e=d[1])?e.match(i):!1)&&f[2]){d=document.createElement("script");d.src=f[2];if((g=e.match(j))&&g[2])d.charset=g[2];d.async=!0;c.appendChild(d)}else(k=d[2])&&0<k.length&&this._globalEval(k)},isDaily:function(){return/daily\.taobao\.net/.test(window.location.hostname)?!0:!1}})},{requires:["node","sizzle","json"]});
