(function(b,g){"function"===typeof define&&define.amd?define("zepto-gfx",["zepto"],function(b){g(b)}):g(b.Zepto)})(this,function(b){var g={duration:400,easing:""},h=/webkit/i.test(navigator.appVersion)?"webkit":"moz",i="-"+h+"-";n={transition:i+"transition",transform:i+"transform",transitionEnd:h+"TransitionEnd"};var j="scale,scaleX,scaleY,scale3d,rotate,rotateX,rotateY,rotateZ,rotate3d,translate,translateX,translateY,translateZ,translate3d,skew,skewX,skewY,matrix,matrix3d,perspective".split(",");
Array.prototype.indexOf||(Array.prototype.indexOf=function(b,d){for(var c=d||0,a=this.length;c<a;c++)if(this[c]===b)return c;return-1});b.fn.transform=function(e){var d=[],c;for(c in e)if(j.indexOf(c)!==-1){d.push(c+"("+e[c]+")");delete e[c]}d.length&&(e[n.transform]=d.join(" "));return b(this).css(e)};b.fn.gfxPopIn=function(e,d){var c=b(this),a=b.extend({},g,e||{});a.scale=a.scale||0.2;c.transform({"-webkit-transform-origin":"50% 50%","-moz-transform-origin":"50% 50%",scale:a.scale,opacity:"0",display:"block"}).animate({scale:"1",
opacity:"1"},a.duration,a.easing,d)};b.fn.gfxPopOut=function(e,d){var c=b(this),a=b.extend({},g,e||{});a.scale=a.scale||0.2;c.transform({"-webkit-transform-origin":"50% 50%","-moz-transform-origin":"50% 50%",scale:"1",opacity:"1"}).animate({opacity:0,scale:a.scale},a.duration,a.easing,function(){c.transform({display:"none",opacity:1,scale:1});d&&d()})};b.fn.gfxFadeIn=function(e,d){var c=b(this),a=b.extend({},g,e||{});a.duration=a.duration||1E3;c.css({opacity:0}).show().animate({opacity:1},a.duration,
a.easing,d)};b.fn.gfxFadeOut=function(e,d){var c=b(this),a=b.extend({},g,e||{});c.css({opacity:1}).animate({opacity:0},a.duration,a.easing,function(){c.hide().css({opacity:1});d&&d()})};b.fn.gfxShake=function(e,d){var c=b(this),a=b.extend({},g,e||{}),f,k=function(){c.animate({translateX:f+"px"},a.duration,a.easing,function(){c.transform({translateX:0});d&&d()})},h=function(){c.animate({translateX:"-"+f+"px"},a.duration,a.easing,k)};a.duration=a.duration||100;a.easing=a.easing||"ease-out";f=a.distance||
20;c.animate({translateX:"-"+f+"px"},a.duration,a.easing,function(){c.animate({translateX:f+"px"},a.duration,a.easing,h)})};b.fn.gfxBlip=function(e,d){var c=b(this),a=b.extend({},g,e||{});a.scale=a.scale||1.15;c.animate({scale:a.scale},a.duration,a.easing,function(){c.animate({scale:1},a.duration,a.easing,d)})};b.fn.gfxExplodeIn=function(e,d){var c=b(this),a=b.extend({},g,e||{});a.scale=a.scale||3;c.transform({scale:a.scale,opacity:0,display:"block"}).animate({scale:1,opacity:1},a.duration,a.easing,
d)};b.fn.gfxExplodeOut=function(e,d){var c=b(this),a=b.extend({},g,e||{}),f=d;a.reset&&(f=second);a.scale=a.scale||3;c.transform({scale:1,opacity:1}).animate({scale:a.scale,opacity:0},a.duration,a.easing,f)};b.fn.gfxFlipIn=function(e,d){var c=b(this),a=b.extend({},g,e||{});c.transform({rotateY:"180deg",scale:0.8,display:"block"}).animate({rotateY:0,scale:1},a.duration,a.easing,d)};b.fn.gfxFlipOut=function(e,d){var c=b(this),a=b.extend({},g,e||{}),f=d;a.reset&&(f=function(){c.transform({scale:1,rotateY:0,
display:"none"});d&&d()});c.transform({rotateY:0,scale:1}).animate({rotateY:"-180deg",scale:0.8},a.duration,a.easing,f)};b.fn.gfxRotateOut=function(e,d){var c=b(this),a=b.extend({},g,e||{}),f=d;first=function(){c.transform({rotateY:0,display:"none"});d&&d()};a.reset&&(f=first);c.transform({rotateY:0}).animate({rotateY:"-180deg"},a.duration,a.easing,f)};b.fn.gfxRotateIn=function(e,d){var c=b(this),a=b.extend({},g,e||{});c.transform({rotateY:"180deg",display:"block"}).animate({rotateY:0},a.duration,
a.easing,d)};b.fn.gfxSlideOut=function(e,d){var c=b(this),a=b.extend({},g,e||{}),f,h;a.direction=a.direction||"right";f=a.distance||100;a.direction==="left"&&(f=f*-1);f=f+"%";h=a.fade?0:1;c.show().animate({translate3d:f+",0,0",opacity:h},a.duration,a.easing,function(){c.transform({translate3d:"0,0,0",opacity:1}).hide();d&&d()})};b.fn.gfxSlideIn=function(e,d){var c=b(this),a=b.extend({},g,e||{}),f;a.direction=a.direction||"right";f=a.distance||100;a.direction==="left"&&(f=f*-1);c.transform({translate3d:f+
"%,0,0",opacity:a.fade?0:1}).show().animate({translate3d:"0,0,0",opacity:1},a.duration,a.easing,d)}});KISSY.add("mobile/zepto-gfx/",function(){return Zepto});
